добавлена разметка
codajoker/team-3-project pull request #12
Opened 2021-08-14 07:30 UTC by vladislav-borovikov

2021-08-14 11:43 UTC, codajoker requested changes

2021-08-14 11:43 UTC, codajoker commented on src/pages/contact.html
>  <!DOCTYPE html>
Вы не работаете в папке pages ваша папка это partial в этой папке только я могу что-то  изменять !

2021-08-14 17:45 UTC, vladislav-borovikov commented on src/pages/contact.html
>  <!DOCTYPE html>
поправь пожалуйста тогда исходный файл, я перенесу код в правильный файл

2021-08-15 05:58 UTC, codajoker requested changes

2021-08-15 05:58 UTC, codajoker commented on src/pages/contact.html
> -    <include src="./partials/components/order-form.html"></include>
Влад зачем ты удалил мои компоненты

2021-08-15 05:58 UTC, codajoker commented on src/partials/contact/hero.html
> +    </header>
этого писать не надо

2021-08-15 05:58 UTC, codajoker commented on src/partials/contact/hero.html
> +<body>
Этого тоже

2021-08-15 05:58 UTC, codajoker commented on src/sass/layout/contact/_hero.scss
> +    color: #487996;
Используем переменные

2021-08-15 05:58 UTC, codajoker commented on src/sass/layout/contact/_hero.scss
> +    color: #2B2B2B;
Переменнные

2021-08-15 14:16 UTC, codajoker requested changes

2021-08-15 14:16 UTC, codajoker commented on src/partials/contact/hero.html
> +    <main>
этого не должно быть

2021-08-15 14:16 UTC, codajoker commented on src/partials/contact/hero.html
> +                    <ul class="contact__contact-discription">
Добавь класс list

2021-08-15 14:16 UTC, codajoker commented on src/partials/contact/hero.html
> +                        class="contact__contact-part-discriptionl">3dfreedom.info@gmail.com</a>
Добавь класс link

2021-08-15 14:16 UTC, codajoker commented on src/partials/contact/hero.html
> +    <script src="../index.js"></script>
удали это

2021-08-15 14:16 UTC, codajoker commented on src/sass/layout/contact/_hero.scss
> +    content: "\1F609";
Тут нельзя ничего писать

2021-08-15 14:18 UTC, vladislav-borovikov commented on src/sass/layout/contact/_hero.scss
> +    content: "\1F609";
Там нельзя писать если ты создаешь объект типа линий, а если нам нужен смайлик, то там прописывается код смайла

2021-08-15 14:28 UTC, codajoker approved these changes

2021-08-15 14:31 UTC, merged