Fixed model-exemples section
codajoker/team-3-project pull request #32
Opened 2021-08-15 15:17 UTC by ortbogdan

Пофіксив секцію, забрав лишні маржини, зміним шлях до картинок, добавив флекс-базис для лі

2021-08-15 16:32 UTC, codajoker requested changes

2021-08-15 16:32 UTC, codajoker commented on src/partials/3d_printing/model_examples.html
> +                        srcset="../images/tablet/3d-printing/image2.png 1x, /images/tablet/3d-printing/image2@2x.png 2x" />
Две точки путь

2021-08-15 19:00 UTC, ortbogdan commented on src/partials/3d_printing/model_examples.html
> +                        srcset="../images/tablet/3d-printing/image2.png 1x, /images/tablet/3d-printing/image2@2x.png 2x" />
Пофіксив

2021-08-16 07:34 UTC, codajoker approved these changes

2021-08-16 07:35 UTC, merged